/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as PublicLayoutRouteImport } from './routes/public/_layout'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as PublicLayoutIndexRouteImport } from './routes/public/_layout/index'
import { Route as AdminLayoutIndexRouteImport } from './routes/admin/_layout/index'
import { Route as PublicLayoutMyBorrowRouteImport } from './routes/public/_layout/my-borrow'
import { Route as PublicLayoutBooksRouteImport } from './routes/public/_layout/books'
import { Route as AdminLayoutUsersRouteImport } from './routes/admin/_layout/users'
import { Route as AdminLayoutSettingsRouteImport } from './routes/admin/_layout/settings'
import { Route as AdminLayoutItemsRouteImport } from './routes/admin/_layout/items'

const PublicRouteImport = createFileRoute('/public')()
const AdminRouteImport = createFileRoute('/admin')()

const PublicRoute = PublicRouteImport.update({
  id: '/public',
  path: '/public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLayoutRoute = PublicLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => PublicRoute,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AdminRoute,
} as any)
const PublicLayoutIndexRoute = PublicLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const AdminLayoutIndexRoute = AdminLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const PublicLayoutMyBorrowRoute = PublicLayoutMyBorrowRouteImport.update({
  id: '/my-borrow',
  path: '/my-borrow',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicLayoutBooksRoute = PublicLayoutBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const AdminLayoutUsersRoute = AdminLayoutUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutSettingsRoute = AdminLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutItemsRoute = AdminLayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AdminLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/public': typeof PublicLayoutRouteWithChildren
  '/admin/items': typeof AdminLayoutItemsRoute
  '/admin/settings': typeof AdminLayoutSettingsRoute
  '/admin/users': typeof AdminLayoutUsersRoute
  '/public/books': typeof PublicLayoutBooksRoute
  '/public/my-borrow': typeof PublicLayoutMyBorrowRoute
  '/admin/': typeof AdminLayoutIndexRoute
  '/public/': typeof PublicLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AdminLayoutIndexRoute
  '/public': typeof PublicLayoutIndexRoute
  '/admin/items': typeof AdminLayoutItemsRoute
  '/admin/settings': typeof AdminLayoutSettingsRoute
  '/admin/users': typeof AdminLayoutUsersRoute
  '/public/books': typeof PublicLayoutBooksRoute
  '/public/my-borrow': typeof PublicLayoutMyBorrowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/public': typeof PublicRouteWithChildren
  '/public/_layout': typeof PublicLayoutRouteWithChildren
  '/admin/_layout/items': typeof AdminLayoutItemsRoute
  '/admin/_layout/settings': typeof AdminLayoutSettingsRoute
  '/admin/_layout/users': typeof AdminLayoutUsersRoute
  '/public/_layout/books': typeof PublicLayoutBooksRoute
  '/public/_layout/my-borrow': typeof PublicLayoutMyBorrowRoute
  '/admin/_layout/': typeof AdminLayoutIndexRoute
  '/public/_layout/': typeof PublicLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/public'
    | '/admin/items'
    | '/admin/settings'
    | '/admin/users'
    | '/public/books'
    | '/public/my-borrow'
    | '/admin/'
    | '/public/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/public'
    | '/admin/items'
    | '/admin/settings'
    | '/admin/users'
    | '/public/books'
    | '/public/my-borrow'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/admin/_layout'
    | '/public'
    | '/public/_layout'
    | '/admin/_layout/items'
    | '/admin/_layout/settings'
    | '/admin/_layout/users'
    | '/public/_layout/books'
    | '/public/_layout/my-borrow'
    | '/admin/_layout/'
    | '/public/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRoute
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  AdminRoute: typeof AdminRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/public': {
      id: '/public'
      path: '/public'
      fullPath: '/public'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/_layout': {
      id: '/public/_layout'
      path: '/public'
      fullPath: '/public'
      preLoaderRoute: typeof PublicLayoutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/public/_layout/': {
      id: '/public/_layout/'
      path: '/'
      fullPath: '/public/'
      preLoaderRoute: typeof PublicLayoutIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/admin/_layout/': {
      id: '/admin/_layout/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminLayoutIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/public/_layout/my-borrow': {
      id: '/public/_layout/my-borrow'
      path: '/my-borrow'
      fullPath: '/public/my-borrow'
      preLoaderRoute: typeof PublicLayoutMyBorrowRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/public/_layout/books': {
      id: '/public/_layout/books'
      path: '/books'
      fullPath: '/public/books'
      preLoaderRoute: typeof PublicLayoutBooksRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/admin/_layout/users': {
      id: '/admin/_layout/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminLayoutUsersRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/settings': {
      id: '/admin/_layout/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminLayoutSettingsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/items': {
      id: '/admin/_layout/items'
      path: '/items'
      fullPath: '/admin/items'
      preLoaderRoute: typeof AdminLayoutItemsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
  }
}

interface AdminLayoutRouteChildren {
  AdminLayoutItemsRoute: typeof AdminLayoutItemsRoute
  AdminLayoutSettingsRoute: typeof AdminLayoutSettingsRoute
  AdminLayoutUsersRoute: typeof AdminLayoutUsersRoute
  AdminLayoutIndexRoute: typeof AdminLayoutIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutItemsRoute: AdminLayoutItemsRoute,
  AdminLayoutSettingsRoute: AdminLayoutSettingsRoute,
  AdminLayoutUsersRoute: AdminLayoutUsersRoute,
  AdminLayoutIndexRoute: AdminLayoutIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

interface AdminRouteChildren {
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PublicLayoutRouteChildren {
  PublicLayoutBooksRoute: typeof PublicLayoutBooksRoute
  PublicLayoutMyBorrowRoute: typeof PublicLayoutMyBorrowRoute
  PublicLayoutIndexRoute: typeof PublicLayoutIndexRoute
}

const PublicLayoutRouteChildren: PublicLayoutRouteChildren = {
  PublicLayoutBooksRoute: PublicLayoutBooksRoute,
  PublicLayoutMyBorrowRoute: PublicLayoutMyBorrowRoute,
  PublicLayoutIndexRoute: PublicLayoutIndexRoute,
}

const PublicLayoutRouteWithChildren = PublicLayoutRoute._addFileChildren(
  PublicLayoutRouteChildren,
)

interface PublicRouteChildren {
  PublicLayoutRoute: typeof PublicLayoutRouteWithChildren
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLayoutRoute: PublicLayoutRouteWithChildren,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRoute,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  AdminRoute: AdminRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
